<?php
//$Id$

/**
 * implementation of hook menu
 */
function views_deploy_menu() {
  $items = array();
  $plans = deploy_get_plans();

  if (!empty($plans)) {
    $items['admin/build/views/deploy'] = array(
      'title' => 'Deploy',
      'description' => 'Add a view to a deployment plan.',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('views_deploy_add_form', $plans),
      'access arguments' => array('add items to deployment plan'),
      'type' => MENU_LOCAL_TASK
    );
  }
  
  return $items;
}

/**
 * deploy view form
 */
function views_deploy_add_form($form_state, $plans) {
  $views = array();
  $result = db_query("SELECT name FROM {views_view} ORDER BY name");
  while ($view = db_fetch_array($result)) {
    $views[$view['name']] = $view['name'];
  }
  
  if (!empty($views)) {
    $form['pid'] = array(
      '#title' => t('Deployment Plan'),
      '#type' => 'select',
      '#options' => $plans,
      '#description' => t('The deployment plan to add this view to'),
    );
    $form['view_name'] = array(
      '#title' => t('View'),
      '#type' => 'select',
      '#multiple' => TRUE,
      '#required' => TRUE,
      '#options' => $views,
      '#description' => t('The view to deploy'),
    );
    $form['submit'] = array(
      '#type' => 'submit',
      '#value' => t('Add to deployment plan'),
    );

    return $form;
  }
  else {
    drupal_set_message('You have no views available to deploy');
  }

}

/**
 * deploy view form submit callback
 */
function views_deploy_add_form_submit($form, &$form_state) {
  $pid = $form_state['values']['pid'];
  $module = 'views';

  foreach ($form_state['values']['view_name'] as $view_name) {
    $description = "View: $view_name";
    deploy_add_to_plan($pid, $module, $description, $view_name);
  }

  $form_state['redirect'] = "admin/build/deploy/list/$pid";
}

/**
 * deploy view form validation callback
 */
function views_deploy_add_form_validate($form, &$form_state) {
  foreach ($form_state['values']['view_name'] as $view_name) {
    $result = db_query("select iid from {deploy_plan_items} where module = 'views' and pid = %d and data = '%s'", $form_state['values']['pid'], $view_name);
    if (db_result($result)) {
      form_set_error('view_name', t("View $view_name already exists in the deployment plan."));
    }
  }
}

/**
 * deploy view deployment 'hook'
 */
function views_deploy($url, $api_key, $view_name) {
  $view = views_get_view($view_name);
  if (is_null($view)) {
    drupal_set_message(t("View $view_name does not exist."));
  }
  
  $export = views_create_view_code($view_name);

  return xmlrpc($url, 'views.importView', $api_key, $export);
}
