<?php

/**
 * Implementation of hook_deploy_endpoints().
 */
function deploy_service_pubsub_deploy_services() {
  $path = drupal_get_path('module', 'deploy_service_pubsub') . '/plugins';
  return array(
    'DeployServicePubSub' => array(
      'name' => 'PubSubHubBub service',
      'description' => 'Defines a PubSubHubBub service that clients or sub sites can fetch content from.',
      'handler' => array(
        'class' => 'DeployServicePubSub',
        'file' => 'DeployServicePubSub.inc',
        'path' => $path,
      ),
    ),
  );
}

/**
 * Implementation of hook_menu().
 */
function deploy_service_pubsub_menu() {
  $items = array();

  $items['deploy/pubsub/%deploy_plan'] = array(
    'title' => t('PubSubHubBub service'),
    'page callback' => 'deploy_service_pubsub_page',
    'page arguments' => array(3, 4),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
    'file' => 'deploy_service_pubsub.pages.inc',
  );

  return $items;
}
