<?php

/**
 * Implementation of hook_deploy_endpoints().
 */
function deploy_endpoint_atom_deploy_endpoints() {
  $path = drupal_get_path('module', 'deploy_endpoint_atom') . '/plugins';
  return array(
    'DeployEndpointAtom' => array(
      'name' => 'Atom endpoint',
      'description' => 'Adds an Atom endpoint for this deployment plan where clients or sub sites can fetch content from.',
      'handler' => array(
        'class' => 'DeployEndpointAtom',
        'file' => 'DeployEndpointAtom.inc',
        'path' => $path,
      ),
    ),
  );
}

/**
 * Implementation of hook_menu().
 */
function deploy_endpoint_atom_menu() {
  $items = array();

  $items['deploy/endpoint/atom/%deploy_plan/%deploy_endpoint'] = array(
    'title' => t('Atom deployment endpoint'),
    'page callback' => 'deploy_endpoint_atom_page',
    'page arguments' => array(3, 4),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
    'file' => 'deploy_endpoint_atom.pages.inc',
  );

  return $items;
}
