<?php

/**
 * Implementation of hook_menu().
 */
function deploy_ui_menu() {
  $items = array();

  $items['admin/structure/deploy/plans/list/%ctools_export_ui/empty'] = array(
    'title' => 'Empty',
    'description' => 'Remove all content from the plan',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('deploy_ui_empty_plan_form', 5),
    'access arguments' => array('administer deployments'),
    'file' => 'deploy_ui.pages.inc',
    'type' => MENU_LOCAL_ACTION,
  );

  $items['admin/structure/deploy/plans/list/%ctools_export_ui/flatten'] = array(
    'title' => 'Remove Duplicates',
    'description' => 'Remove duplicate content from the plan',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('deploy_ui_flatten_plan_form', 5),
    'access arguments' => array('administer deployments'),
    'file' => 'deploy_ui.pages.inc',
    'type' => MENU_LOCAL_ACTION,
  );

  $items['admin/structure/deploy/plans/list/%ctools_export_ui/manage'] = array(
    'title' => 'Manage',
    'description' => 'Manage the contents of the plan',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('deploy_ui_manage_plan_form', 5),
    'access arguments' => array('administer deployments'),
    'file' => 'deploy_ui.pages.inc',
    'type' => MENU_LOCAL_ACTION,
  );

  return $items;
}

/**
 * Implements hook_theme().
 */
function deploy_ui_theme() {
  return array(
    'deploy_ui_plan_view' => array(
      'render_element' => 'vars',
      'template' => 'deploy-ui-plan-view',
      'path' => drupal_get_path('module', 'deploy_ui') . '/templates',
    ),
    'deploy_ui_overview_plan_content' => array(
      'variables' => array('info' => array()),
      'file' => 'deploy_ui.pages.inc',
    ),
  );
}

/**
 * Implementation of hook_ctools_plugin_directory().
 */
function deploy_ui_ctools_plugin_directory($module, $plugin) {
  if ($module == 'ctools' && $plugin == 'export_ui') {
    return 'plugins/' . $plugin;
  }
}
