<?php

/**
 * Implementation of hook_deploy_endpoints().
 */
function deploy_endpoint_atom_deploy_endpoints() {
  $path = drupal_get_path('module', 'deploy_endpoint_atom') . '/plugins';
  return array(
    'DeployEndpointAtom' => array(
      'name' => 'Atom endpoint',
      'description' => 'Adds an Atom endpoint for this deployment plan where clients or sub sites can fetch content from.',
      'handler' => array(
        'class' => 'DeployEndpointAtom',
        'file' => 'DeployEndpointAtom.inc',
        'path' => $path,
      ),
    ),
  );
}
