<?php
// $Id$

/**
 * @file
 * Interface to deploy content types between servers
 *
 * NOTE: This only works with Drupal 6.11 or higher. Lower versions will
 * cause deployments to fail once they reach the first content type.
 */
include_once ('./'. drupal_get_path('module', 'node') .'/content_types.inc');

/**
 * Implementation of hook menu().
 */
function content_copy_deploy_menu() {
  $items = array();
  $plans = deploy_get_plan_options();

  if (!empty($plans)) {
    $items['admin/content/types/deploy'] = array(
      'title' => 'Deploy',
      'description' => 'Add a content type to a deployment plan.',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('content_copy_deploy_add_form', $plans),
      'access arguments' => array('add items to deployment plan'),
      'file' => './content_copy_deploy.pages.inc',
      'type' => MENU_LOCAL_TASK
    );
  }

  return $items;
}

/**
 * Deploy content deployment 'hook'.
 */
function content_copy_deploy($content_type) {
  // There is a bug in batch API up through Drupal 6.10 that causes batch API
  // to fail when a callback runs drupal_execute(). content_copy_export() is
  // one such function, thereore we return an error if running an older
  // version. For more info on this issue see [#297972].
  $version = explode('.', VERSION);
  $minor_version = explode('-', $version[1]);
  if ((int)$minor_version < 11) {
    xmlrpc_error($xmlrpcusererr + 1, t('Content type deployment requires Drupal 6.11 or greater on the deploying server.'));
    return FALSE;
  }

  if (module_exists('fieldgroup')) {
    $groups = array_keys(fieldgroup_groups($content_type));
  }

  $fields = array_values(content_copy_fields($content_type));

  $values = array(
    'type_name' => $content_type,
    'groups' => $groups,
    'fields' => $fields,
  );

  $export = content_copy_export($values);
  
  return deploy_send(array('content_copy.import'), array($content_type, $export));
}

