<?php

/**
 * @file
 * This is the class that is responsible for sorting out dependencies and
 * ordering among them all.
 */

class DeployEntityIterator implements RecursiveIterator {

  function __construct($entity_ids) {

  }

  function hasChildren() {

  }

  function getChildren() {

  }

  function current() {

  }

  function key() {

  }

  function rewind() {

  }

  function valid() {

  }

}
