<?php

/**
 * Implementation of hook_deploy_providers().
 */
function deploy_provider_views_deploy_providers() {
  $path = drupal_get_path('module', 'deploy_provider_views') .'/plugins';
  return array(
    'DeployProviderViews' => array(
      'name' => 'Views provider',
      'description' => 'Provides content to a deployment plan by executing a user defined view.',
      'handler' => array(
        'class' => 'DeployProviderViews',
        'file' => 'DeployProviderViews.inc',
        'path' => $path,
      ),
    ),
  );
}
